var latitudeDestaque=$("#latitudeDestImovel").val();var longitudeDestaque=$("#longitudeDestImovel").val();var enderecoCompleto=$("#enderecoCompletoEmpresaAqui").val();var map;var infowindow;var myLatlng;var marker=[];var service;var aPlaces=[];var markeres=[];var radio="";function initialize(){myLatlng=new google.maps.LatLng(latitudeDestaque,longitudeDestaque);var a={zoom:14,center:myLatlng};map=new google.maps.Map(document.getElementById("map-canvas"),a);var b=pathSite+"media/imagens/mapa.png";markerfull=new google.maps.Marker({position:myLatlng,map:map,icon:b,animation:google.maps.Animation.DROP});var c=enderecoCompleto;google.maps.event.addListener(markerfull,"click",function(){$("<div>"+c+"</div>").dialog({title:"EndereÃ§o do imÃ³vel",resizable:false,draggable:false,buttons:[{text:"Ok",click:function(){$(this).dialog("close")}}]})})}function createMarker(a){var b={url:a.icon,size:new google.maps.Size(71,71),origin:new google.maps.Point(0,0),anchor:new google.maps.Point(17,34),scaledSize:new google.maps.Size(25,25)};marker=new google.maps.Marker({position:a.geometry.location,icon:b,map:map});markeres.push(marker);google.maps.event.addListener(marker,"click",function(){$('<div><img style="float:left; width:50px; padding-right:5px;" src="'+a.icon+'"/>'+a.name+"<br/>"+a.vicinity+"</div>").dialog({title:"Estabelecimento",resizable:false,draggable:false,buttons:[{text:"Ok",click:function(){$(this).dialog("close")}}]})})}function addRadius(){radio=new google.maps.Circle({center:myLatlng,radius:1600,strokeColor:"red",strokeOpacity:0.1,strokeWeight:1,fillColor:"red",fillOpacity:0.1});radio.setMap(map)}function clearOverlays(){for(var a=0;a<markeres.length;a++){markeres[a].setMap(null)}}function addPlaces(b,a){var c={location:myLatlng,radius:1500,types:b};infowindow=new google.maps.InfoWindow();service=new google.maps.places.PlacesService(map);service.nearbySearch(c,callback)}function callback(c,a){if(a==google.maps.places.PlacesServiceStatus.OK){for(var b=0;b<c.length;b++){createMarker(c[b])}}}$(function(){$(".map__control input").click(function(){aPlaces=[];$(".map__control input:checked").each(function(a){aPlaces[a]=$(this).val()});clearOverlays();if(aPlaces!=""){addPlaces(aPlaces,1500);if(radio==""){addRadius()}}else{radio.setMap(null);radio=""}})});if(latitudeDestaque&&longitudeDestaque){google.maps.event.addDomListener(window,"load",initialize)};



/*
<input type="hidden" id="latitudeDestImovel" name="latitudeDestImovel" value="<?php echo $aImovel->getLatitude();?>"/>
			<input type="hidden" id="longitudeDestImovel" name="longitudeDestImovel" value="<?php echo $aImovel->getLongitude();?>"/>
			<input type="hidden" id="enderecoCompletoEmpresaAqui" name="enderecoCompletoEmpresaAqui" value="<?= $aImovel->getEndereco().' '.($aImovel->getComplemento() ? ' - ' . $aImovel->getComplemento() : '').', '.$bairroNome->getNmsetor().', '.$cidadeNome->getNmcidade()?>"/>
			<ul class="map__control mapa_busca_legendas legendas" style="text-decoration: none; margin: 0px; padding: 0px;">
			<li><img src="<?php echo $this->baseUrl();?>/media/_img/iconesMapa/OQkz4rM9DsVqmALvgm9UNp4lCkT4eDdIv6Ldeq0zasG.png" alt="Academias"/><label><input type="checkbox" value="gym" data-icon="https://d1h8v8ecaokgwa.cloudfront.net/static/OQkz4rM9DsVqmALvgm9UNp4lCkT4eDdIv6Ldeq0zasG.png"/> Academias</label></li>
			<li><img src="<?php echo $this->baseUrl();?>/media/_img/iconesMapa/6EdUSF98JTYZWIlVeqDIgElA871AYy5P4k8Ul40kACy.png" alt="Bancos"/><label><input type="checkbox" value="bank" data-icon="https://d1h8v8ecaokgwa.cloudfront.net/static/6EdUSF98JTYZWIlVeqDIgElA871AYy5P4k8Ul40kACy.png"/> Bancos</label></li>
			<li><img src="<?php echo $this->baseUrl();?>/media/_img/iconesMapa/EgqfWOHfmiMwGHGmUZ83KFqc2L80gGHYWL3NtyvFboL.png" alt="Bar"/><label><input type="checkbox" value="bar" data-icon="https://d1h8v8ecaokgwa.cloudfront.net/static/EgqfWOHfmiMwGHGmUZ83KFqc2L80gGHYWL3NtyvFboL.png"/> Bares</label></li>
			<li><img src="<?php echo $this->baseUrl();?>/media/_img/iconesMapa/dnAxzgdnIX8Mv9C0LPSs1BHgP76ixlqFfBnHSUfgcUe.png" alt="Correios"/><label><input type="checkbox" value="post_office" data-icon="https://d1h8v8ecaokgwa.cloudfront.net/static/dnAxzgdnIX8Mv9C0LPSs1BHgP76ixlqFfBnHSUfgcUe.png"/> Correios</label></li>
			<li><img src="<?php echo $this->baseUrl();?>/media/_img/iconesMapa/S3Y3RV3PQEOXp51lI5waA3AOglHm97FFDl2wCrN0eVT.png" alt="Escolas"/><label><input type="checkbox" value="school" data-icon="https://d1h8v8ecaokgwa.cloudfront.net/static/S3Y3RV3PQEOXp51lI5waA3AOglHm97FFDl2wCrN0eVT.png"/> Escolas</label></li>
			<li><img src="<?php echo $this->baseUrl();?>/media/_img/iconesMapa/liOi5dI7YNkiYrg4VFE8SrJelHq4ZzAahDqZbWiqOpQ.png" alt="Farm&aacute;cias"/><label><input type="checkbox" value="pharmacy" data-icon="https://d1h8v8ecaokgwa.cloudfront.net/static/liOi5dI7YNkiYrg4VFE8SrJelHq4ZzAahDqZbWiqOpQ.png"/> Farm&aacute;cias</label></li>
			<li><img src="<?php echo $this->baseUrl();?>/media/_img/iconesMapa/22pnjJyKT10RHNH6aYPHMyXw4RTn5V4HfNDQH4YB9Ns.png" alt="Hospitais"/><label><input type="checkbox" value="hospital" data-icon="https://d1h8v8ecaokgwa.cloudfront.net/static/22pnjJyKT10RHNH6aYPHMyXw4RTn5V4HfNDQH4YB9Ns.png"/> Hospitais</label></li>
			<li><img src="<?php echo $this->baseUrl();?>/media/_img/iconesMapa/qeCO4zFFvL7BTrCjzGdp8RzHsJaQNzXjlFkiN3vIA9a.png" alt="Igrejas"/><label><input type="checkbox" value="church" data-icon="https://d1h8v8ecaokgwa.cloudfront.net/static/qeCO4zFFvL7BTrCjzGdp8RzHsJaQNzXjlFkiN3vIA9a.png"/> Igrejas</label></li>
			<li><img src="<?php echo $this->baseUrl();?>/media/_img/iconesMapa/68juwjkqwNuHHHs2r1GoZA7qs9Dzm7nM0djG1Aox5tE.png" alt="Locadoras"/><label><input type="checkbox" value="movie_rental" data-icon="https://d1h8v8ecaokgwa.cloudfront.net/static/68juwjkqwNuHHHs2r1GoZA7qs9Dzm7nM0djG1Aox5tE.png"/> Locadoras</label></li>
			<li><img src="<?php echo $this->baseUrl();?>/media/_img/iconesMapa/MSZiMGweLgz6oEh1Mt7fFxdX2cFVUzXuUilMClsCOYN.png" alt="Mercados"/><label><input type="checkbox" value="grocery_or_supermarket" data-icon="https://d1h8v8ecaokgwa.cloudfront.net/static/MSZiMGweLgz6oEh1Mt7fFxdX2cFVUzXuUilMClsCOYN.png"/> Mercados</label></li>
			<li><img src="<?php echo $this->baseUrl();?>/media/_img/iconesMapa/iVwJe7EJWiRom0VjwOTCqV3LM29OaQXXooVFwosslXw.png" alt="Padarias"/><label><input type="checkbox" value="bakery" data-icon="https://d1h8v8ecaokgwa.cloudfront.net/static/iVwJe7EJWiRom0VjwOTCqV3LM29OaQXXooVFwosslXw.png"/> Padarias</label></li>
			<li><img src="<?php echo $this->baseUrl();?>/media/_img/iconesMapa/jcq5LDa2oVUQqzANqUXM9mLK7sz6a9E6vt2lbC8Aiws.png" alt="Pol&iacute;cia"/><label><input type="checkbox" value="police" data-icon="https://d1h8v8ecaokgwa.cloudfront.net/static/jcq5LDa2oVUQqzANqUXM9mLK7sz6a9E6vt2lbC8Aiws.png"/> Pol&iacute;cia</label></li>
			</ul>
			<div id="map-canvas" style="width:500px; height: 300px;">
				
			</div>


*/